runtime: php74
api_version: 1

runtime_config:
  document_root: public 

skip_files:
  .env 
env_variables:
  APP_ENV: production
  APP_KEY: base64:6qS4VOsj3gT9qQacx2snIVYtyZUW1ec3i8mDNyVNcxc=
  # Agrega otras variables de entorno según sea necesario

handlers:
- url: /(.+\.php)$
  script: \1
