runtime: php55
api_version: 1

runtime_config:
  document_root: public 

skip_files:
  .env 

env_variables:
  APP_LOG:errorlog
  APP_KEY:base64:6qS4VOsj3gT9qQacx2snIVYtyZUW1ec3i8mDNyVNcxc=
  STORAGE_DIR: /tmp
  
handlers:
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true
# Serve php scripts.
- url: /(.+\.php)$
  script: \1
